version: '3.9'

services:
    mysql:
        container_name: db
        build: 
            context: ./mysql
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: sample_db
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            TZ: 'Asia/Tokyo'
        volumes:
            - ./mysql/db:/docker-entrypoint-initdb.d  #初期データ
        ports:
            - '3306:3306'
        networks: 
            - app-tier

    frontend:
        container_name: frontend
        build: 
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
          -  ./frontend:/usr/src/app
          -  /usr/src/app/node_modules/
        ports:
          -  3000:3000
        networks: 
          -  app-tier
    
    api:
        container_name: api
        build: 
            context: ./api
            dockerfile: Dockerfile
        volumes:
          -  ./api:/app
        ports:
            - '5000:5000'
        links:
            - mysql
        tty: true
        networks: 
            - app-tier

networks:
    app-tier:
        driver: bridge